[package]
name = "keiba_scraping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.0", features = ["blocking"] }
scraper = "0.13.0"
log = "0.4.0"
env_logger = "0.9.0"
chrono = "0.4.0"
unicode-normalization = "0.1.0"